version: '3'

services:
  front-north:
    image: romtretjakov2017/front-north:latest
    ports:
      - "5000:5000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  back-north:
    image: romtretjakov2017/back-north:latest
    ports:
      - "5001:5001"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db-north:
    image: romtretjakov2017/db-north:latest
    ports:
      - "5002:5002"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"